### ISSUE TITLE
GameClient - Display video

### ISSUE THREAD

**Issue by jackjackrene** [jackjackrene/SAD_Pi#20]
As a GameClient I want to display the video feed from the web-cam because the Operator needs to see the visual.

**Comment by thomasericdean** [comment]
ID: #20
 Name: Display Video
 Pre-Condition: Webcam must be plugged in with application at the start screen.  
 Normal Steps: 
1. Open application. 
2. Video display will be on screen by default. 
 Alternative Steps: There are no alternative steps. The video will be displayed with an option to turn it off.  
Post-Condition: Operator is able to see a view of the playing field inside a window in the application.

**Comment by jackjackrene** [comment]
Video displays, with start and stop buttons. Video is not interrupted by move and fire.
