### ISSUE TITLE
GameClient - Reload Command

### ISSUE THREAD

**Issue by jackjackrene** [jackjackrene/SAD_Pi#24]
As a GameClient I want a reload command because when I reload missiles I need the software to display the new amount.

**Comment by thomasericdean** [comment]
ID: #24
Name: Reload Button
Pre-Condition: The missile launcher must have launched at least one missile to reload. 
Normal Steps: 
1. Click Game. 
2. Click Reload. 
Alternative Steps: There are no alternative steps. The only way to reload is by clicking Game>Reload. 
Post-Condition: The number of missiles in the launcher has been reset to the total number of missiles.

**Comment by jadmr** [comment]
Implemented in SADMissileLauncher with signature defined in ISADMissileLauncher
