### ISSUE TITLE
GameClient - detect how many missiles are left

### ISSUE THREAD

**Issue by jackjackrene** [jackjackrene/SAD_Pi#3]
As a GameClient I want to be able to detect how many missiles are left because I need to know when there are no missiles left.

**Comment by thomasericdean** [comment]
![image](https://cloud.githubusercontent.com/assets/8562578/6052634/eedd9234-ac89-11e4-87cf-6bb87c112f6e.png)

**Comment by thomasericdean** [comment]
ID: #3
    Name: Missile Detection
    Pre-Condition: Knowing how many missiles have been fired. 
    Normal Steps:
1. Fire a shot. 
2. Increment # of shots fired. 
3. Subtract total # of missiles by # of shots fired. 
    Alternative Steps:N/A
    Post-Condition: All missiles are fired.

**Comment by jadmr** [comment]
Implemented in CurrentMissileCount filed and updated in Fire method in DreamCheekyMissileLauncher
