### ISSUE TITLE
GameClient - calibrate 

### ISSUE THREAD

**Issue by jackjackrene** [jackjackrene/SAD_Pi#4]
As a GameClient I want to be able to calibrate because the missiles need to hit targets as shown on the screen.

**Comment by thomasericdean** [comment]
ID: #4
    Name: Calibrate
    Pre-Condition: The rocket must be placed at the zero position with missiles in the missile launcher. 
    Normal Steps: 
1. Place rocket at zero position with missiles in the launcher. 
2. Ensure rocket is lined up perfectly parallel with playing field. 
3. Run calibration function/procedure. 
    Alternative Steps:
    Post-Condition: The rocket will be placed at the zero position with the trajectory of the missile calibrated to a preset zero position, ready to fire.

**Comment by jackjackrene** [comment]
The missile launcher currently moves to 0,0 at every Move command. I have calibrated the launcher so that it moves approximately the same degrees that are entered in Move or MoveBy. The degrees needed to be converted to time for the Dream Cheeky missile launcher implementation.
