### ISSUE TITLE
Display number of missiles left

### ISSUE THREAD

**Issue by jackjackrene** [jackjackrene/SAD_Pi#61]

**Comment by jadmr** [comment]
Whose doing this? Was it me? XD

Whoever is implementing this is also implementing the direction D-Pad thing and the positions of the MSL. If it's not me whose assigned, let me know regardless because I need to wrap methods to allow you to move in a certain direction

**Comment by thomasericdean** [comment]
Finished with help from Lamarche. Do not set two viewModels within the same .xaml page. It will instantiate two different viewModels.
